# Introduction

Sablefish (*Anoplopoma fimbria*) are managed in British Columbia (BC) using trap, longline and trawl gear as part of as part of the Integrated Fisheries Management Plan (IFMP). Over the ten year span of `r yr-9` to `r yr`,  BC fishermen have landed an average of `r format(avgTen, big.mark=",")` metric tons of sablefish annually.  The majority of sablefish in `r yr`  were captured by longline hook gear (`r LonglineP`\%) and longline trap gear (`r trapP`\%). Commercial harvest of sablefish typically occurs at depths up to 985 fathoms, along the steep-walled slopes off the west coast of Haida Gwaii (formerly Queen Charlotte Islands), in the complex troughs  of Queen  Charlotte Sound, and in the steep canyons and ridges off the west coast of  Vancouver Island. 

Fishery-independent research and assessment surveys for sablefish have been conducted in BC coastal waters since 1988. Survey procedures have evolved over time, but each year they have consisted of fishing sets using trap gear at randomly selected and/or index sites. These surveys are used to obtain catch rate data, gather biological samples, capture oceanographic measurements and collect tag release and recapture data. In turn, this information is used as the key contemporary index of abundance for assessing the biological status of the sablefish stock, and to condition an operating model that serves as the biological basis of the coastal Management Strategy Evaluation [@Cox2011].

The design of the sablefish survey has remained consistent since 2011, and has been comprised of stratified random sampling (StRS) for sites along BC’s continental shelf and the continuation of sampling at standardized index sites at four mainland inlets.  For details about past survey designs, see the historic overview provided by [@Wyeth2003] and [@Wyeth2004b]. For details on specific surveys conducted from 1988 through 1993 see [@Smith1996]; for surveys in 1994 and 1995 see [@Downes1997]; for surveys from 1996 to 2000 see [@Wyeth2003].  For the 2001 through 2006 surveys see [@Wyeth2003], [@Wyeth2004a], [@Wyeth2004b] and [@Wyeth2006], respectively.  

In order to evaluate the impact of fishing gear on the benthic habitat, a pilot study began in 2012 to capture images from traps.  In addition, exploratory sets were conducted in a Vancouver Island inlet near Quatsino Sound to assess for sablefish density and/or size composition.  In this technical report we describe survey operations and summarize data collected on the `r yr` chartered survey aboard the F/V `r boat`. 