# Methods

## SURVEY DESIGN

Methodology for the `r yr` sablefish research and assessment survey employed a stratified random sampling component, a traditional component, an exploratory study and a benthic impacts study (Table \@ref(tab:table1)).

 
### STRATIFIED RANDOM SAMPLING SURVEY COMPONENT

Since 2011, the StRS design has been conducted in all offshore survey areas. The StRS design began in 2003 with the purpose of distributing tag releases at random, collecting biological samples and developing a catch-rate based index of abundance [@Wyeth2003]. It also provided an alternative design to the historic traditional offshore component of the survey (1990 to 2010) which occured at fixed locations. 

Under the StRS design, the offshore survey area is partitioned into five spatial strata (S~1~ to S~5~) and three depth strata (RD~1~ to RD~3~) for a total of 15 (Figure \@ref(fig:figure1)). The five spatial strata are S~1~ (South West Coast Vancouver Island or SWCVI), S~2~ (North West Coast Vancouver Island or NWCVI), S~3~ (Queen Charlotte Sound or QCS), S~4~ (South West Coast of Haida Gwaii or SWCHG), and S~5~ (North West Coast of Haida Gwaii or NWCHG).  The three targeted depth ranges are 100-250 fathoms (RD~1~), 250-450 fathoms (RD~2~), and 450-750 fathoms(RD~3~). The area within each of the 15 strata are sectioned into 2 km x  2 km grid cells or ‘fishing blocks’ from which set locations are randomly chosen (Figure \@ref(fig:figure2)). 

From 2003 through 2005, five grid cells were randomly selected in each spatial-depth stratum. From 2006 through 2010, the number was increased to six. In 2011, the allocation of the blocks to strata were optimized and used in the 2012 survey (Table \@ref(tab:table2)).

### TRADITIONAL SURVEY COMPONENT 

Standardized fishing sets under the traditional component of the survey have specific gear, bait, and sampling protocols. The original intent of the standardized sets was to collect catch rate data in order to index trends in abundance, tag fish and obtain biological samples. In 2010 the offshore portion of the traditional standardized survey was terminated as it was shown that the continued use of the standardized survey, in combination with the StRS, resulted in greater frequencey for stock assessment errors [@Cox2011]. Since then only standardized fishing sets within four mainland inlet localities have continued. A string of 25 traps were set at five specific localities in each of the following four areas: Portland Inlet, Gil Island, Finlayson Channel, and Dean/Burke Channel (Table \@ref(tab:table1)). Trap gear was deployed near the center of each of the five inlet boundaries in order to avoid the steep slopes characteristic of these channels/fjords (Figure \@ref(fig:figure3)).

### EXPLORATORY COMPONENT

Two fishing sites for the exploratory component were visited in 2011 and 2012 to evaluate Vancouver Island inlets for sablefish density and/or size composition (Table \@ref(tab:table1)).  

### BENTHIC IMPACTS STUDY

In order to evaluate the impact of fishing gear on the benthic habitat, camera sets were initiated during the 2012 Sablefish research and assessment survey.  Nuytco autonomous camera systems were attached to traps to capture video and still images. In addition, accelerometers were deployed on traps to gather trap orientation and movement data.  

## VESSEL

The `r yr` survey of `r setcnt` sets was chartered aboard the F/V `r boat` (Figure \@ref(fig:figure4)), skippered by `r captain`  between `r dates`, `r yr` (Appendix \@ref(app:first-appendix)). Information about the vessel can be found at [\underline{http://marinetraffic.com}](http://marinetraffic.com). 

## FISHING GEAR

The longline trap gear consisted of a groundline resting on the ocean floor with 25 baited traps attached to beckets at 150 foot intervals along its length and 90 pound anchors at each end (Figure \@ref(fig:figure5), a). A flagpole was required for at least one end of the set to improve visibility for retrieval. The traps  were steel frame with a bottom hoop diameter of 54 inches and covered with an North American #84 black braided nylon web of 2.75 inch mesh (Figure \@ref(fig:figure5), b). The tunnels were made of green braided, knotless, 1.25 inch mesh. The traps did not include escape rings; but instead a ‘rot panel’  of # 21 cotton located above the middle ring. 

Standard bait bags (6 by 12 inches) made of 1/8 inch web with a nylon drawstring and #7 stainless trolling snaps were included with the traps. 

## FISHING OPERATIONS

During normal survey fishing operations gear was deployed on alternate days. Prior to deployment, the Fishing Master inspected the block to determine fishability and if it was within the targeted depth range.  The goal was to have as much gear as possible within the block boundaries.  If unfishable, the survey protocol requires that an alternate block is to be chosen to the east, west, north, and south, respectively. If none of those blocks meet the criteria, an alternate block of the same area and depth strata was randomly chosen.  

Two science staff recorded information associated with the deployment of the gear. One science member was positioned in the wheelhouse and recorded set details on the bridge log data form. The start and end geo-referenced positions of each set were entered at the time when the first and last traps were set over the stern. Depths were recorded at one-minute intervals between the first and last anchors being set. Later, the duration of the set was calculated as the time elapsed between the first anchor being set over the stern and the first anchor hauled aboard (Appendix \@ref(app:second-appendix), Figure B.1).

A set log was filled out on the deck by the science recorder who had maximum visibility of the crew setting the traps over the stern rail. The set log included the time and identity of the first and last buoys, anchor time, a tally of beckets and traps, as well as the unique identifying numbers of sensors deployed (Appendix \@ref(app:second-appendix), Figure B. 2)

### STRATIFIED RANDOM SAMPLING SURVEY DESIGN COMPONENT

Sets in StRS blocks had a targeted soak time of 24 hours.  Fishing sets were designated useable if hauled between 22 and 26 hours. Traps were baited with 10 pounds of loose offshore Pacific hake (*Merluccius productus*) and 2 pounds of bagged squid.

### TRADITIONAL STANDARD SURVEY COMPONENTS

Standardized fishing sets under the traditional component of the survey have specific gear, bait, and sampling protocols. The original intent of the standardized sets was to collect catch rate data in order to index trends in abundance, tag fish and obtain biological samples. In 2010 the offshore portion of the traditional standardized survey was terminated as it was shown that the continued use of the standardized survey, in combination with the StRS, resulted in greater frequencey for stock assessment errors [@Cox2011]. Since then, standardized fishing sets under the traditional component have occured at the four mainland inlet localities. A string of 25 traps were set at five specific localities in each of the following four areas: Portland Inlet, Gil Island, Finlayson Channel, and Dean/Burke Channel. Trap gear was deployed near the center of each of the five locality boundaries in order to avoid the steep slopes characteristic of these channels/fjords (Figure \@ref(fig:figure3)).

### VANCOUVER ISLAND INLETS EXPLORATORY COMPONENT

To assess those areas that have not been surveyed for sablefish density and/or size composition, two exploratory sets were conducted in a Vancouver Island inlet near Quatsino Sound. These two sets were conducted in the immediate vicinity of the two exploratory sets that were done in the 2011 survey (Figure \@ref(fig:figure2)).

## CATCH PROCESSING

Haulback speed allowed the science crew to accurately record catch. The charter catch log data form (Appendix \@ref(app:second-appendix), Figure B.3) was completed during hauling by the science staff recorder positioned at the Marel M1100 scale.  Each trap number, trap use code (D=dump, A=age sample, B=length sex maturity biosample, T=tag sample, MT=empty trap), and trap species counts and weights were recorded. Crew members alerted the recorder about any damage to a trap (i.e. holes) which was then recorded.  The next day, the entries on charter catch log form were transposed to tabular format on the charter catch log entry form (Appendix \@ref(app:second-appendix), Figure B.4).

### Sablefish Allocation Details
 
Sablefish were tagged from 1/3 of the traps on StRS sets and 1/2 of the traps on the inlet sets. Due to high catch numbers, the survey protocol was revised in 2018 to designate ~125 sablefish to be tagged (T) from 1/3 of the traps on all sets.  When catches were high, traps targeted for tagging were spread throughout the string to avoid tagging the first 125 fish.  A biological sample was collected from the coded "A" traps with the goal of selecting 50 to 60 fish.  If CPUE was high, the new survey protocol of 2018 designated a minimal of two traps to be used for samples.  If both traps contained more than 60 sablefish, a random process was used to select ~60 specimens.

The remaining traps were allocated to the discard category and sorted by size into either legal (D) or sublegal (SD) discards. The SD (sublegal discards) code was added during the 2017 survey to account for the large numbers of juvenile sablefish and facilitate their quick return to the ocean. Legal discards (D) of sablefish were kept by the vessel and processed as commercial catch. 

## BIOLOGICAL SAMPLING (LWSMO)

Biological samples were collected from sablefish and rougheye/blackspotted rockfish (*Sebastes aleutianus/Sebastes melanostictus*) specimens. Measurements were recorded for fork length (L), body weight (W), sex (S) and maturity level (M) (Appendix \@ref(app:second-appendix), Figure B.5). Sagittal otoliths (O) were collected and stored for potential ageing by the sclerochronology laboratory.  In addition, tissue for DNA was collected from the rougheye/blackspotted rockfish complex for later species determination.  Since this complex of two distinct species [@Orr2008] have similar appearances with slight variations in colour markings and dorsal fin lengths, the sampler visually identifed each specimen as either a rougheye, a blackspotted or a hybrid species.  All rockfish and legal-sized sablefish (fork length > 55 cm) that were sacrificed for biological samples were dressed, frozen, and landed as commercial catch (Appendix \@ref(app:second-appendix), Figure B.5).

Length and sex were collected from all other species on the LengthSexSpecies form (Appendix \@ref(app:second-appendix), Figure B.6).

## SABLEFISH TAGGING

Tagging became part of the annual sablefish research and assessment survey in 1991 (@Wyeth2003).  Fish destined to be tagged were transferred from the sorting area to a tagging tank.  A scientist stood at the sample station and tagged fish with a Mark II Long Tagging gun loaded with Floy FD-94 T-bar anchor tags.  The tag was inserted on the left side of the fish, 1 cm below and 2-3 cm behind the anterior insertion of the first dorsal fin.  Fork length (mm) measurements were taken. Before release, any sampling errors, injuries or damage to the fish were recorded on the tagging form by a second scientist. Tag checks were performed systematically to ensure tag numbers on the data form matched those on the fish specimen (Appendix \@ref(app:second-appendix), Figure B.7).

## SABLEFISH TAG RECOVERY

Any previously tagged fish brought aboard may have been treated in one of two ways.  First, sablefish with Canadian tags were re-released with a new tag and the previous tag was removed. In addition, any wounds from the old tag were recorded.  Second, sablefish with a foreign agency tag or sablefish that had sustained numerous injuries were retained for biological sampling.  Foreign tags were later returned to their country of origin (Appendix \@ref(app:second-appendix), Figure B.8).

During survey years 1992 through 1997 and 2004, previously tagged sablefish were re-released with the same tag. New tagging protocols of replacing the tag began in 2005.

## TAGGING NORTH PACIFIC SPINY DOGFISH

In each spatial stratum, several spiny dogfish with intact first dorsal spines and pre-caudal lengths greater than seventy centimetres were tagged with pop-off satellite tags for Auke Bay Laboratories (ABL).   First, the recorder noted the set number, tag number, pre-caudal length and sex on the data sheet.  The sampler then drilled a horizontal hole through the first dorsal spine and inserted a piece of monofilament that was attached to a pop-off satellite tag. The monofilament was secured with a crimping sleeve.  Once the spiny dogfish had been observed in the recovery tank for a few minutes, it was released over the side of the boat.


```{r SensorText, echo=FALSE}
   # -- determine the sets that deployed SBE and HOBO and CTD
   sense  <-  paste("select Year, SUM(SBE39) AS SBE39, SUM(HOBO) AS HOBO, ",
                    "SUM(CTD) AS CTD, SUM(CAM) AS CAM ",
                    "from dbo.Report_SBE_HOBO_IND ",
                    "group by Year having (Year =", yr,")", sep="")
   #sensor  <-  GetSQLData(sense,"Sablefish")
   #write.table(sensor, file = paste(path,"methods01.csv",sep=''),row.names=FALSE, na="",col.names=TRUE,  sep=",") 
   sensor <-  read.csv(paste(path,'methods01.csv',sep=''), header=T)
   
```

## OCEANOGRAPHIC SENSOR DATA COLLECTION

A Sea-bird Bird SBE 39 temperature and pressure logger was placed in a protective plastic pipe and attached to the inside of the third trap during gear deployment. Typically, data from the sensor was immediately downloaded after hauling using the Sea-Bird Electronics SeaTerm © software.  Standard file format provided readings of temperature, pressure, date and time. 

## BENTHIC IMPACTS STUDY 

This study was launched in testing phase to investigate gear interaction with bottom substrate.  Designated traps with outfitted with a Nuytco autonomous camera system and a HOBO Pendant G logger (accelerometer) bolted to a trap (Appendix \@ref(app:third-appendix), Figure C.1 a). The camera system consisted of a GoPro Hero HD camera designed to image at depths up to 1500 m for up to 48 hours.  The motherboard allowed for configuration of image mode (still or video), camera activation depth, interval of imaging events, clip length (video mode only) and LED lighting brightness (Appendix \@ref(app:third-appendix), Figure C.1 b).  The loggers contained an internal three-axis accelerometer that measured acceleration of motion of the traps in units of g-force (m/s$^2$).   Data from the camera units and accelerometers were processed after the pilot camera sets were hauled.


## ELECTRONIC MONITORING VIDEO DATA COLLECTION  

During haulback, the vessel’s electronic monitoring (EM) cameras were activated by the skipper.  Three internet protocol (IP) cameras and three standard analog cameras were positioned at optimal viewing angles to record the survey activities.  IP camera 6 and analog cameras 1 and 3 were positioned along the mast to record the catch as it was processed at the hopper.   IP camera 5 and analog camera 2 were positioned on the starboard to record the traps as they were brought over the rail.  Last, IP camera 4 was positioned over the tagging tank.   The video data from each set was reviewed by the catch recorder and an assistant shortly after the set to allow for quality control prior to the electronic catch data entry process.   


